# Cargo.toml
[package]
name = "spotifyisshit"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
reqwest = { version = "0.11", features = ["json", "stream"] }
rand = "0.8"
